### ISSUE TITLE
(Milestone 1) Editing and submitting the report

### ISSUE THREAD

**Issue by eylulyalcinkaya** [bounswe/bounswe2020group4#202]
- [x] Table of contents will be added. 
- [x] General arrangement (tabs, paragraphs, headers) will be fixed. 
- [x] PDF format of the document will be put to wiki.

Deadline: @23.55 29.11.2020
